### PR TITLE
Feat/manage events api

### PR DESCRIPTION
**Pull request by l3luescreen**

### CODE REVIEW

**Review by loukhin — COMMENTED** [review]
should `databases/schedu-web/event.json` be updated for this year?

cc @tanssw

**Comment by l3luescreen** [comment]
> should `databases/schedu-web/event.json` be updated for this year?
> 
> cc @tanssw

I forget 😢

**Comment by loukhin** [comment]
> > should `databases/schedu-web/event.json` be updated for this year?
> > cc @tanssw
> 
> I forgot 😢

If we're not really using it anyway, i think it's probably better to left it outdated.

**Comment by tanssw** [comment]
> should `databases/schedu-web/event.json` be updated for this year?
> 
> cc @tanssw

yep

**Review by loukhin — APPROVED** [review]
ะๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆๆ

**Pull request merged**
